spring:
  data:
    mongodb:
      database: ${MONGODB_DB}
      uri: mongodb:${MONGODB_URI}



ewardrobe:
  app:
    SecretKey:{SECRET_KEY}

cloudinary:
  cloud-name: your-cloud-name
  api-key: your-api-key
  api-secret: your-api-secret



unsplash:
  clientId: {CLIENT_ID}
  apiUrl: {API_URL}